---
- name: Install Chrony package
  apt:
    name: chrony
    state: present

- name: Configure Chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify:
    - restart chronyd

