---
- name: Install Chrony package
  apt:
    name: chrony
    state: present
  tags:
    - chrony

- name: Configure Chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify:
    - restart chronyd
  tags:
    - chrony
