- name: Check if services exist
  stat:
    path: "/etc/systemd/system/{{ item }}.service"
  register: serv_exist
  loop:
    - ntp
    - ntpd
    - systemd-timedated
    - timesyncd

- name: chrony+allother-
  become: true
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - ntp
    - ntpd
    - systemd-timedated
    - timesyncd
  ignore_errors: yes
  when: 
    - item in serv_exist.results
    - serv_exist.results[loop.index0].stat.exists